# Generated by Django 3.2.23 on 2023-12-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20231202_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_seats',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registered_seats',
        ),
    ]
