# Generated by Django 3.2.23 on 2023-12-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20231207_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='excerpt',
        ),
    ]
