# Generated by Django 3.2.23 on 2023-11-23 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_author_event_user'),
        ('likes', '0002_auto_20231123_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='events.event'),
        ),
    ]
