# Generated by Django 3.2.23 on 2023-12-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='add_to_guest',
            field=models.IntegerField(null=True),
        ),
    ]
