# Generated by Django 3.2.23 on 2023-12-03 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20231202_2322'),
        ('bookings', '0002_booking_add_to_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.event'),
        ),
    ]
